### ISSUE TITLE
input to calTADs

### ISSUE THREAD

**Issue by rdali** [XiaoTaoWang/calTADs#1]
What is the input required for calTADs?

**Comment by huakangjian** [comment]
Hi：
i have a problem that what format for the interactive matrix i want to input it is?

**Comment by XiaoTaoWang** [comment]
Sorry for the delay reply, but I no longer have time to maintain calTADs. I recommend trying my recent software, HiTAD, which is based on more sophisticated algorithm and well-documented. HiTAD has been included in my previous package TADLib, and you can get the lastest version from https://pypi.python.org/pypi/TADLib
